name: Tests

on: ["pull_request", "push"]

jobs:
  tests:
    name: "Unit tests"
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        php:
          - "7.4"
          - "8.0"
          - "8.1"
        operating-system:
          - "macos-latest"
          - "ubuntu-20.04"
          - "windows-latest"
        dependencies:
          - "stable"
          - "highest"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
        env:
          update: true

      - name: "Set PHP platform for 8.1 alpha"
        if: ${{ matrix.php-version == '8.1' }}
        run: composer config platform.php 8.0

      - name: Setup Problem Matchers
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Fix PHPUnit Version PHP < 7.4
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "phpunit/phpunit:^6.5.14 || ^7.5.20 || ^8.5.8" --dev --no-update --no-interaction
        if: "matrix.php < 7.4"

      - name: Fix PHPUnit Version PHP >= 7.4
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require "phpunit/phpunit:^9.5.8" --dev --no-update --no-interaction
        if: "matrix.php >= 7.4"

      - name: "Set PHP platform for 8.1 alpha"
        if: ${{ matrix.php-version == '8.1' }}
        run: composer config platform.php 8.0

      - name: "Install dependencies (Composer)"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Execute PHPUnit
        run: vendor/bin/phpunit
